spring.application.name=twoWheelerFinance

server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/customer
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

#Gmail setup
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gauravpaul549@gmail.com
spring.mail.password=sfge wsiq lzfp dlha
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

